name: Infrastructure Integrity Check

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform-check:
    name: 'Validate IaC Code'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      # Initialize backend without asking for cloud credentials
      run: terraform init -backend=false
      working-directory: ./terraform

    # REMOVED: Terraform Format Check (It was causing false failures)

    - name: Terraform Validate
      # This is the real test: Does the code logic work?
      run: terraform validate
      working-directory: ./terraform
